import { precacheAndRoute } from 'workbox-precaching';

// Use the precache manifest generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const options = {
      body: data.body || 'New message received',
      icon: data.icon || '/logo.png',
      badge: data.badge || '/logo.png',
      tag: data.id || data.tag || Math.random().toString(), // Force unique tag
      renotify: true,
      vibrate: [200, 100, 200],
      data: {
        url: data.data?.url || data.url || '/'
      }
    };

    event.waitUntil(
      self.registration.showNotification(data.title || 'Arcadian Works ERP', options)
    );
  } catch (error) {
    console.error('Push Event Error:', error);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = event.notification.data.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // Check if there is already a window open with this URL
        for (let i = 0; i < windowClients.length; i++) {
          const client = windowClients[i];
          if (client.url.includes(urlToOpen) && 'focus' in client) {
            return client.focus();
          }
        }
        // If no window is open, open a new one
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      })
  );
});
